<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9ropiP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9ropiP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ9ropiP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ9ropiP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ9ropiP\App_KernelDevDebugContainer([
    'container.build_hash' => 'J9ropiP',
    'container.build_id' => 'c3f3f596',
    'container.build_time' => 1773132262,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9ropiP');
